trigger:
- '*'

stages:
- stage: 'DeployToTest'
  displayName: 'Deploy to Test'
  dependsOn: [] 
  jobs:
  - job: Deploy
    displayName: 'Deploy job'
    pool:
      vmImage: 'windows-latest'
    steps:
    - script: echo Deploying to test environment...

- stage: 'DeployToProd'
  displayName: 'Deploy to Production'
  dependsOn: []  # Remove this line if you want them to run truly in parallel
  jobs:
  - job: Deploy
    displayName: 'Deploy job'
    pool:
      vmImage: 'windows-latest'
    steps:
    - script: echo Deploying to production environment...
