trigger:
- main

stages:
- stage: BuildApp
  displayName: 'Build Apps'
  jobs:
  - job: BuildFrontendApp
    displayName: 'Build Frontend App'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - script: echo building frontend app
      displayName: 'Build Frontend App'
    - script: echo running unit tests for frontend app
      displayName: 'Unit Tests Frontend'

  - job: BuildBackendApp
    displayName: 'Build Backend App'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - script: echo building backend app
      displayName: 'Build Backend App'
    - script: echo running unit tests for backend app
      displayName: 'Unit Tests Backend'

- stage: DeployDev
  displayName: 'Deploy to DEV environment'
  jobs:
  - job: DeployFrontendDev
    displayName: 'Deploy Frontend to DEV'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - script: echo deploying frontend app to DEV
      displayName: 'Deploy Frontend to DEV'
  - job: DeployBackendDev
    displayName: 'Deploy Backend to DEV'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - script: echo deploying backend app to DEV
      displayName: 'Deploy Backend to DEV'

- stage: DeployProd
  displayName: 'Deploy to PROD environment'
  jobs:
  - job: DeployFrontendProd
    displayName: 'Deploy Frontend to PROD'
    pool:
      vmImage: 'macOS-10.14'
    steps:
    - script: echo deploying frontend app to PROD
      displayName: 'Deploy Frontend to PROD'
  - job: DeployBackendProd
    displayName: 'Deploy Backend to PROD'
    pool:
      vmImage: 'vs2017-win2016'
    steps:
    - script: echo deploying backend app to PROD
      displayName: 'Deploy Backend to PROD'
